Updated the government interest sampler query to generate 5 samples o…
PatentsView/PatentsView-DB pull request #106
Opened 2021-12-15 02:54 UTC by bethanne-card

…n a patent_id level rather than a row level

2021-12-15 18:24 UTC, patentsview-admin requested changes

2021-12-15 18:24 UTC, patentsview-admin commented on QA/government_interest/GovtInterestTester.py
> +       LEFT JOIN patent.government_organization go
@bethanne-card  Can you switch this to use the database name from the config ? The key I believe is "RAW_DB"

2021-12-20 22:54 UTC, sarvothaman approved these changes

2021-12-20 22:54 UTC, sarvothaman approved these changes

2021-12-20 22:55 UTC, merged