Q2 2022
PatentsView/PatentsView-DB pull request #110
Opened 2022-04-15 15:39 UTC by bethanne-card

Added in patent_crosswalk query into the pipeline. I also added in some QA work to move organization_name from first name or last name and a QA check.

2022-04-15 19:57 UTC, jbutler-air commented
A couple notes:
on accuracy/robustness:
* Fix_rawassignee_wrong_org corrects for both cases where an assignee has first name but not last and last name but not first, but test_rawassignee_org only checks for first name with no last name. We can add an ‘OR’ condition to the test_rawassignee_org query (example 1 below)
* fix_rawassignee_wrong_org checks for a string match of keywords in the last name, but not in the first name; is this an intentional difference, or should the function the same?
* fix_rawassignee_wrong_org changes all ‘type’ values to 2 when it moves a name from first or last name to org name, but doesn’t check that the organizations are US-based (international orgs get type=3). We can either incorporate a ‘CASE WHEN’ phrase into the ‘SET’ clause, or we can run two otherwise identical queries where one makes the name change and sets type=2 where country=US and the other makes the name change and sets type=3 where country<>US. (Example 2 below)

on efficiency:
* We should be able to get around the temporary tables in fix_rawassignee_wrong_org - I think we can just do “SET organization = name_{first/last}, type = {2/3}, name_{first/last} = NULL” - my understanding is these will resolve in order and set org to name before changing name to null. (Example 2 below) 

SELECT COUNT(*)
FROM rawassignee
WHERE (name_first IS NOT NULL AND name_last IS NULL)
OR (name_first IS NULL AND name_last IS NOT NULL)


UPDATE rawassignee
SET organization = name_{first/last}, name_{first/last} = NULL, type = (CASE WHEN country = ‘US’ THEN ‘2’ ELSE ‘3’)
WHERE where name_{first/last} IS NOT NULL 
AND name_{last/first} IS NULL
AND name_{first/last} REGEXP ‘{keywords}’

2022-04-15 20:42 UTC, bethanne-card commented
Thanks for looking into this Jack!

So there are logic differences between the two cases for a reason. When there is first_name and no last name, we assume that all those entries are an organization and can move first_name entries to the organization column and then easily check for it. In the case of last name with no first name, if you look at the data, some of the names look like an actual last name while some of the rows are organizations. I did my best to subset the organizations and move those rows from last_name to organization. We can not write a simple test since not all of the rows are able to be moved with certainty. Come to think of it, we can at least make sure that all the rows with organization-related substrings were moved over.

Do you want to add that test or I can?

Thanks again! Happy Friday 😄
BA
________________________________
From: Jack Butler ***@***.***>
Sent: Friday, April 15, 2022 1:57 PM
To: PatentsView/PatentsView-DB ***@***.***>
Cc: Card, Beth Anne ***@***.***>; Author ***@***.***>
Subject: Re: [PatentsView/PatentsView-DB] Q2 2022 (PR #110)

External email alert: Be wary of links & attachments.


A couple notes:
on accuracy/robustness:

  *   Fix_rawassignee_wrong_org corrects for both cases where an assignee has first name but not last and last name but not first, but test_rawassignee_org only checks for first name with no last name. We can add an ‘OR’ condition to the test_rawassignee_org query (example 1 below)
  *   fix_rawassignee_wrong_org checks for a string match of keywords in the last name, but not in the first name; is this an intentional difference, or should the function the same?
  *   fix_rawassignee_wrong_org changes all ‘type’ values to 2 when it moves a name from first or last name to org name, but doesn’t check that the organizations are US-based (international orgs get type=3). We can either incorporate a ‘CASE WHEN’ phrase into the ‘SET’ clause, or we can run two otherwise identical queries where one makes the name change and sets type=2 where country=US and the other makes the name change and sets type=3 where country<>US. (Example 2 below)

on efficiency:

  *   We should be able to get around the temporary tables in fix_rawassignee_wrong_org - I think we can just do “SET organization = name_{first/last}, type = {2/3}, name_{first/last} = NULL” - my understanding is these will resolve in order and set org to name before changing name to null. (Example 2 below) 

SELECT COUNT(*)
FROM rawassignee
WHERE (name_first IS NOT NULL AND name_last IS NULL)
OR (name_first IS NULL AND name_last IS NOT NULL)

UPDATE rawassignee
SET organization = name_{first/last}, name_{first/last} = NULL, type = (CASE WHEN country = ‘US’ THEN ‘2’ ELSE ‘3’)
WHERE where name_{first/last} IS NOT NULL
AND name_{last/first} IS NULL
AND name_{first/last} REGEXP ‘{keywords}’

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPatentsView%2FPatentsView-DB%2Fpull%2F110%23issuecomment-1100343406&data=05%7C01%7Cbcard%40air.org%7Ca3f068baa0ad4d7364be08da1f1a27cf%7C9ea45dbc7b724abfa77cc770a0a8b962%7C0%7C0%7C637856494451118681%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kNLD55XExRqzCAj8LMitBO7c8wm0QpLFpLCW55VDPFY%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWGZG2EQMICF7GKJ5PXBQB3VFHC2FANCNFSM5TQWU6KA&data=05%7C01%7Cbcard%40air.org%7Ca3f068baa0ad4d7364be08da1f1a27cf%7C9ea45dbc7b724abfa77cc770a0a8b962%7C0%7C0%7C637856494451118681%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=i1EEf%2Bt3kac44r%2BAOewHnGn0ofnISOQRaBep%2Bys1AX4%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-04-28 17:44 UTC, sarvothaman commented on lib/utilities.py
> +            print("/tNo Content Length Attached")
What's with the `/t`? do you mean `\t`?

2022-04-30 23:04 UTC, sarvothaman requested changes

2022-04-30 23:04 UTC, sarvothaman commented on airflow/dags/reporting_database_generation/generate-reporting-db.py
> +create_granted_patent_crosswalk = PythonOperator(task_id='create_granted_patent_crosswalk',
Are there no other DAGs that's is better suited for this task? Technically, this belong to "raw database" creation. Further the bulk download process is understood as dependent on raw database creation and considered ready to start as soon raw database is done. Having this task here may introduce inconsistencies

2022-04-30 23:04 UTC, sarvothaman commented on QA/generic_tests.py
> +def update_to_granular_version_indicator(table, db):
I thought i saw a version of this already defined elsewhere? In any case, this function and the `update_version_indicator` should move out of QA folder. (Perhaps into lib/utilities.py?)

2022-05-06 14:42 UTC, sarvothaman commented on updater/xml_to_sql/post_processing.py
> +def fix_rawassignee_wrong_org(config):
Is there a risk of false positives here? i.e. records we thought were organization was in reality just someone with just first name. ( https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/ ) . If the existing data supports the theory that in _patent_ data, this seems to be the case most/all of the time, then I would suggest creating "audit" records to keep track of which records were changed in post processing.

2022-05-06 21:56 UTC, sarvothaman commented
@bethanne-card  I don't have anything else. Feel free to merge when you are ready

2022-05-06 22:08 UTC, merged

2022-10-11 08:24 UTC, bethanne-card commented
We do keep a record in a table called temp_rawassignee_org_fixes_nf

or do you mean we should have more of a generalized table that keeps track of records changed from any table?

________________________________
From: Sarvothaman Madhavan ***@***.***>
Sent: Friday, May 6, 2022 8:42 AM
To: PatentsView/PatentsView-DB ***@***.***>
Cc: Card, Beth Anne ***@***.***>; Author ***@***.***>
Subject: Re: [PatentsView/PatentsView-DB] Q2 2022 (PR #110)

External email alert: Be wary of links & attachments.


@sarvothaman commented on this pull request.

________________________________

In updater/xml_to_sql/post_processing.py<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPatentsView%2FPatentsView-DB%2Fpull%2F110%23discussion_r866868597&data=05%7C01%7Cbcard%40air.org%7C3caac61dcd7d4e78205908da2f6ea9ce%7C9ea45dbc7b724abfa77cc770a0a8b962%7C0%7C0%7C637874449601795406%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cGmXh4sNEbzVFaTI%2F0EnTMdhCd%2FLU%2BbRgjKv6s9OYSo%3D&reserved=0>:

> @@ -246,11 +246,76 @@ def trim_rawassignee(config):
         (name_last IS NULL) AND
         (organization IS NULL);""")

+def fix_rawassignee_wrong_org(config):


Is there a risk of false positives here? i.e. records we thought were organization was in reality just someone with just first name. ( https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.kalzumeus.com%2F2010%2F06%2F17%2Ffalsehoods-programmers-believe-about-names%2F&data=05%7C01%7Cbcard%40air.org%7C3caac61dcd7d4e78205908da2f6ea9ce%7C9ea45dbc7b724abfa77cc770a0a8b962%7C0%7C0%7C637874449601795406%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=px77TPHZMNxAIGs31qdXVK2GCDsH69ueDvSrXt9kdXA%3D&reserved=0> ) . If the existing data supports the theory that in patent data, this seems to be the case most/all of the time, then I would suggest creating "audit" records to keep track of which records were changed in post processing.

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPatentsView%2FPatentsView-DB%2Fpull%2F110%23pullrequestreview-964713427&data=05%7C01%7Cbcard%40air.org%7C3caac61dcd7d4e78205908da2f6ea9ce%7C9ea45dbc7b724abfa77cc770a0a8b962%7C0%7C0%7C637874449601795406%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ecTLhSeRk2IqBw9pDWA4x0A2IKMG%2FcsSxpQOrZBEev4%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWGZG2DX7MZ5TEC6DHZI4I3VIUVVZANCNFSM5TQWU6KA&data=05%7C01%7Cbcard%40air.org%7C3caac61dcd7d4e78205908da2f6ea9ce%7C9ea45dbc7b724abfa77cc770a0a8b962%7C0%7C0%7C637874449601795406%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KGp1HlNZrdWLEbGFzpYhzcy6ink60cGFwvlAm3ajhbY%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-10-11 09:26 UTC, bethanne-card commented
I meant we’ll need more info (what- rawassignee, where – pgpubs,  when – date of change , who – update pipeline) to be stored in that table if it’s going to be automated. The table name itself can answer some of that info (for eg. rawasisgnee_org tells us its rawassignee).

Also don’t temp_ tables trigger a QA failure? Perhaps a different prefix make sense?

Thanks,
Sarvo
From: Card, Beth Anne ***@***.***>
Date: Friday, May 6, 2022 at 1:04 PM
To: PatentsView/PatentsView-DB ***@***.***>, Madhavan, Sarvothaman ***@***.***>
Subject: Re: [PatentsView/PatentsView-DB] Q2 2022 (PR #110)
We do keep a record in a table called temp_rawassignee_org_fixes_nf

or do you mean we should have more of a generalized table that keeps track of records changed from any table?

________________________________
From: Sarvothaman Madhavan ***@***.***>
Sent: Friday, May 6, 2022 8:42 AM
To: PatentsView/PatentsView-DB ***@***.***>
Cc: Card, Beth Anne ***@***.***>; Author ***@***.***>
Subject: Re: [PatentsView/PatentsView-DB] Q2 2022 (PR #110)

External email alert: Be wary of links & attachments.

@sarvothaman commented on this pull request.

________________________________

In updater/xml_to_sql/post_processing.py<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPatentsView%2FPatentsView-DB%2Fpull%2F110%23discussion_r866868597&data=05%7C01%7Csmadhavan%40air.org%7Cbcf59c37d0c84f98e7dc08da2f827350%7C9ea45dbc7b724abfa77cc770a0a8b962%7C0%7C0%7C637874534572614922%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Z5IAZ5XVupuWaRdOFEt7hfPmR1yuqwZBRbXVM4M%2FsCY%3D&reserved=0>:

> @@ -246,11 +246,76 @@ def trim_rawassignee(config):

         (name_last IS NULL) AND

         (organization IS NULL);""")



+def fix_rawassignee_wrong_org(config):

Is there a risk of false positives here? i.e. records we thought were organization was in reality just someone with just first name. ( https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.kalzumeus.com%2F2010%2F06%2F17%2Ffalsehoods-programmers-believe-about-names%2F&data=05%7C01%7Csmadhavan%40air.org%7Cbcf59c37d0c84f98e7dc08da2f827350%7C9ea45dbc7b724abfa77cc770a0a8b962%7C0%7C0%7C637874534572614922%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hsMG88eJj274T8cnqRHGj9ZXFTgb3MG2tBWFxAK9Grw%3D&reserved=0> ) . If the existing data supports the theory that in patent data, this seems to be the case most/all of the time, then I would suggest creating "audit" records to keep track of which records were changed in post processing.

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPatentsView%2FPatentsView-DB%2Fpull%2F110%23pullrequestreview-964713427&data=05%7C01%7Csmadhavan%40air.org%7Cbcf59c37d0c84f98e7dc08da2f827350%7C9ea45dbc7b724abfa77cc770a0a8b962%7C0%7C0%7C637874534572614922%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=e4PiYIqk57r7t%2Fno3jujqbqTAJ7Bdg%2BiyY%2Fxp1TxaaM%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWGZG2DX7MZ5TEC6DHZI4I3VIUVVZANCNFSM5TQWU6KA&data=05%7C01%7Csmadhavan%40air.org%7Cbcf59c37d0c84f98e7dc08da2f827350%7C9ea45dbc7b724abfa77cc770a0a8b962%7C0%7C0%7C637874534572614922%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4ujO%2BMbGHsm7QMcYULE5%2BPLXlJp7%2FafwNRA4U04V%2FaE%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>